name: Build Packer Image on AWS with packer container
on:
  push:
    branches:
      - master
  workflow_dispatch: 
env:
  AWS_REGION: "eu-central-1"
jobs:
  build-ami:
    runs-on: ubuntu-latest
    name: Run Packer
    container:
        image: hashicorp/packer:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Run `packer init`
        id: init
        run: "packer init ."

      - name: Run `packer validate`
        id: validate
        run: "packer validate ."
    
      - name: Build Image
        id: build
        run: packer build .