name: Build Packer Image on AWS.
on:
  push:
    branches:
      - master
  workflow_dispatch: 
env:
  AWS_REGION: "eu-central-1"
jobs:
  build-ami:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}  # Change this to your desired region

      - name: Validate AMI with Packer in Docker
        run: |
            docker run --rm -v ${PWD}:/workspace -w /workspace hashicorp/packer:1.10.0 validate .

      - name: Build AMI with Packer in Docker
        run: |
          docker run --rm -v ${PWD}:/workspace -w /workspace hashicorp/packer:1.10.0 build .