name: Build Packer Image on AWS
on:
  push:
    branches:
      - master
  workflow_dispatch: 
env:
  AWS_REGION: "eu-central-1"
  PRODUCT_VERSION: "1.8.6" # or: "latest"
jobs:
  build-ami:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: "packer init ."

      - name: Run `packer validate`
        id: validate
        run: "packer validate ."