name: Build Packer Image on AWS - Create inftrastructure with Terraform - in containers
on:
  push:
    branches:
      - master
  workflow_dispatch: 
env:
  AWS_REGION: "eu-central-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  build-ami:
    runs-on: ubuntu-latest
    name: Run Packer
    container:
        image: hashicorp/packer:latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Run `packer init`
        id: init
        run: "packer init ."

      - name: Run `packer validate`
        id: validate
        run: "packer validate ."
    
      - name: Build Image
        id: build
        run: packer build .
  
  run-instance:
    runs-on: ubuntu-latest
    name: Run Terraform
    needs: build-ami
    container:
      image: hashicorp/terraform:latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        if: needs.build-ami.result == 'success'

      - name: Run `terraform init`
        id: init
        run: "terraform init"

      - name: Run `terraform plan`
        id: plan
        run: "terraform plan"

      - name: Run `terraform apply`
        id: apply
        run: "terraform apply -auto-approve"
